sudo: true
language: c
compiler:
    - gcc
os:
    - linux
before_install:
        - ifconfig
        - sysctl net.core.rmem_max
        - sysctl net.core.rmem_default
        - sysctl -w net.core.rmem_max=212992
        - sysctl -w net.core.rmem_default=212992
        - wget http://dist.schmorp.de/libev/Attic/libev-4.15.tar.gz
        - tar -xzvf libev-4.15.tar.gz
        - cd libev-4.15 && ./configure --prefix=/usr/ && make && sudo make install
        - cd ..
install:
        - git clone https://github.com/regrant/portals4.git
        - ./autogen.sh
        - ./configure --prefix=$HOME/portals4-install/ --with-libev=/usr/lib/ --enable-zero-mrs --enable-transport-udp --enable-reliable-udp --disable-transport-shmem
        - make -j2 check TESTS=""
        - make install
script:
        - export PTL_LOG_LEVEL=3
        - export PTL_DEBUG=1
        - export PTL_IFACE_NAME=lo
#get full output on tests of interest
        - ./src/runtime/hydra/yod.hydra -np 2 ./test/basic/test_ME_put_multiple_large_overlap
        - make check
#        - ./src/runtime/hydra/yod.hydra -np 2 ./test/basic/.libs/test_LE_get
        - cat ./test/basic/test-suite.log
        - cat ./test/sfw/test_n1/test-suite.log 

notifications:
  email:
    recipients:
      - regrant@sandia.gov
    on_success: [change]
    on_failure: [always] 
